"""Pure Agent contracts and fail-closed skeleton.

Importing this package never starts a model, tool, worker, database, or network
operation. Runtime declarations remain fail-closed and persistence is opt-in.
"""

from .action_runtime import (
    ActionLoopDecision,
    ActionObservation,
    ActionReservationIntent,
    AgentActionKind,
    DynamicActionLoopRuntime,
    MainAgentModelDecision,
    ProviderMainAgentActionProvider,
)
from .answer_contracts import (
    AnswerDraft,
    AnswerDraftValidationDecision,
    AnswerLimitationCode,
    ClaimType,
    EpistemicStatus,
    GroundingKind,
    GroundingRecord,
    GroundingSnapshot,
    GroundingStatus,
    InteractionBlock,
    LimitationBlock,
    NarrativeBlock,
    SourceBasis,
    StatementBlock,
)
from .answer_runtime import GroundingIntegrityGuard
from .capabilities import MainAgentRuntimeCapabilities
from .capability_executors import (
    AnswerCapabilityBoundary,
    AnswerCapabilityBoundaryProvider,
    AnswerCapabilityExecutor,
    CapabilityExecutorFactories,
    CapabilityBoundaryUnavailable,
    CapabilityExecutionError,
    CapabilityExecutionRejected,
    DisabledAnswerCapabilityBoundaryProvider,
    DisabledPlanCapabilityBoundaryProvider,
    DisabledToolCallBatchBoundaryProvider,
    PlanCapabilityBoundary,
    PlanCapabilityBoundaryProvider,
    PlanCapabilityExecutor,
    ReplanCapabilityExecutor,
    RequestInformationCapabilityExecutor,
    ToolCallBatchBoundary,
    ToolCallBatchBoundaryProvider,
    ToolCallBatchCapabilityExecutor,
)
from .citation_contracts import (
    CitationAuthorityRecord,
    CitationAuthoritySnapshot,
    CitationBundle,
    CitationProjection,
    CitationProjectionDecision,
    RenderedAnswerCandidate,
)
from .citation_runtime import AnswerBlockRenderer, CitationProjector
from .complexity_gate import DefaultComplexityGate
from .context_runtime import ContextAssemblerRuntime
from .decision_runtime import MainAgentDecisionRuntime
from .intent_runtime import IntentUnderstandingRuntime
from .local_bootstrap import (
    LocalBootstrapError,
    LocalBootstrapStatus,
    LocalPureAgentRuntimeAdapters,
    LocalRuntimeBootstrapRequest,
    LocalRuntimeBootstrapResult,
    LocalRuntimeIsolationGuard,
    bootstrap_local_pure_agent_runtime,
)
from .memory_runtime import MemoryCommitter, MemoryReader
from .deepseek_provider import (
    DeepSeekMainAgentActionProvider,
    OfficialDeepSeekConfig,
    build_official_deepseek_adapter,
)
from .local_runtime_factory import (
    LocalPureAgentCompositionConfig,
    build_local_pure_agent_adapters,
)
from .offline_rag_runtime import (
    CanonicalOfflineRagSources,
    OfflineEvidenceRecord,
    OfflineRagBackend,
    OfflineSearchResult,
)
from .main_agent_boundary import (
    DisabledMainAgentBoundaryInputsProvider,
    MainAgentBoundaryAssemblyInputs,
    MainAgentBoundaryError,
    MainAgentBoundaryInputsProvider,
    MainAgentBoundaryRejected,
    MainAgentTurn,
    PersistedMainAgentDecisionBoundaryProvider,
    PersistedMainAgentTurnResolver,
)
from .planner_runtime import PlannerRuntime
from .persisted_local_adapters import (
    LocalActionAdmissionRule,
    LocalAdmissionPolicy,
    LocalBoundaryInputPolicy,
    PersistedAdmissionContextRejected,
    PersistedLocalAdapterError,
    PersistedLocalBoundaryInputsProvider,
    PersistedLocalBoundaryRejected,
    PersistedLocalRuntimeAdapterFactories,
    PersistedRuntimeAdmissionContextProvider,
)
from .persisted_context_adapters import (
    PersistedConservativeContextTokenCounter,
    PersistedContextAdapterFactories,
    PersistedContextCandidateSource,
    PersistedContextProjectionPolicy,
    PersistedContextSnapshotStore,
)
from .persisted_capability_adapters import (
    PersistedAnswerAuthorityProjector,
    PersistedEvidenceAnswerAuthorityProjector,
    PersistedAnswerAuthorityRejected,
    PersistedAnswerCapabilityBoundaryProvider,
    PersistedCapabilityAdapterError,
    PersistedCapabilityAdapterFactories,
    PersistedCapabilityBoundaryRejected,
    PersistedPlanCapabilityBoundaryProvider,
    PersistedToolBoundaryPolicy,
    PersistedToolCallBatchBoundaryProvider,
    ReceiptOnlyAnswerAuthorityProjector,
)
from .provider_bridges import (
    ProviderIntentUnderstandingProvider,
    ProviderPlannerProvider,
)
from .provider_answer_projection import (
    ProviderAnswerBlockProjection,
    ProviderAnswerProjection,
    ProviderDecisionProjection,
    project_provider_decision,
)
from .provider_runtime import ProviderAdapter, StructuredModelCallBridge
from .registry import INITIAL_TOOL_NAMES, build_initial_registry
from .response_contracts import (
    CommittedResponseArtifact,
    PublishedAnswerMessage,
    ResponseCommitDecision,
    ResponseLifecycleStatus,
    ResponsePersistenceEnvelope,
    ResponseStaleIntent,
    ResponseStaleReason,
    ResponseSupersedeReason,
    ResponseVersionHead,
)
from .response_runtime import AnswerCommitRuntime, ResponseVersionController
from .runtime_guards import (
    ActionAdmissionDecision,
    RuntimeGuardSuite,
    RuntimePolicyCeiling,
    RuntimeProfileSnapshot,
)
from .runtime_controller import (
    ContinuationTokenService,
    DynamicActionControllerDriver,
    LocalRuntimePulseDispatcher,
    PureAgentRuntimeController,
    RunningActionRecoveryContext,
    RunningActionRecoveryController,
    RunningActionRecoveryPlan,
    RuntimeActionRecoveryBinding,
    RuntimeWakeup,
)
from .runtime_composition import (
    CAPABILITY_ACTION_KINDS,
    CapabilityHandlerRegistry,
    CapabilityHandlerRegistrationError,
    FrozenCapabilityHandlerRegistry,
    PureAgentRuntimeComponentFactories,
    PureAgentRuntimeComposition,
    PureAgentRuntimeCompositionRoot,
    RuntimeCompositionError,
    RuntimeCompositionStatus,
    build_capability_handler_registry,
)
from .state import AgentTaskStatus
from .state_machine import create_running_task, decide_transition
from .tool_gateway import CanonicalToolGateway, ToolVisibilityProjector
from .tool_runtime import freeze_registry_snapshot


__all__ = [
    "AgentTaskStatus",
    "AnswerDraft",
    "AnswerDraftValidationDecision",
    "AnswerLimitationCode",
    "AnswerBlockRenderer",
    "AnswerCommitRuntime",
    "ActionLoopDecision",
    "ActionObservation",
    "ActionReservationIntent",
    "ActionAdmissionDecision",
    "AgentActionKind",
    "CanonicalToolGateway",
    "CanonicalOfflineRagSources",
    "CAPABILITY_ACTION_KINDS",
    "CapabilityBoundaryUnavailable",
    "CapabilityExecutorFactories",
    "CapabilityExecutionError",
    "CapabilityExecutionRejected",
    "CapabilityHandlerRegistry",
    "CapabilityHandlerRegistrationError",
    "CitationAuthorityRecord",
    "CitationAuthoritySnapshot",
    "CitationBundle",
    "CitationProjection",
    "CitationProjectionDecision",
    "CitationProjector",
    "ClaimType",
    "CommittedResponseArtifact",
    "ContextAssemblerRuntime",
    "ContinuationTokenService",
    "DefaultComplexityGate",
    "DeepSeekMainAgentActionProvider",
    "DisabledAnswerCapabilityBoundaryProvider",
    "DisabledMainAgentBoundaryInputsProvider",
    "DisabledPlanCapabilityBoundaryProvider",
    "DisabledToolCallBatchBoundaryProvider",
    "DynamicActionLoopRuntime",
    "DynamicActionControllerDriver",
    "EpistemicStatus",
    "GroundingIntegrityGuard",
    "GroundingKind",
    "GroundingRecord",
    "GroundingSnapshot",
    "GroundingStatus",
    "FrozenCapabilityHandlerRegistry",
    "INITIAL_TOOL_NAMES",
    "IntentUnderstandingRuntime",
    "InteractionBlock",
    "LimitationBlock",
    "MainAgentDecisionRuntime",
    "MainAgentBoundaryAssemblyInputs",
    "MainAgentBoundaryError",
    "MainAgentBoundaryInputsProvider",
    "MainAgentBoundaryRejected",
    "MainAgentModelDecision",
    "MainAgentRuntimeCapabilities",
    "MainAgentTurn",
    "LocalRuntimePulseDispatcher",
    "LocalBootstrapError",
    "LocalBootstrapStatus",
    "LocalActionAdmissionRule",
    "LocalAdmissionPolicy",
    "LocalBoundaryInputPolicy",
    "LocalPureAgentRuntimeAdapters",
    "LocalPureAgentCompositionConfig",
    "LocalRuntimeBootstrapRequest",
    "LocalRuntimeBootstrapResult",
    "LocalRuntimeIsolationGuard",
    "MemoryCommitter",
    "MemoryReader",
    "NarrativeBlock",
    "OfflineEvidenceRecord",
    "OfflineRagBackend",
    "OfflineSearchResult",
    "OfficialDeepSeekConfig",
    "PlanCapabilityBoundary",
    "PlanCapabilityBoundaryProvider",
    "PlanCapabilityExecutor",
    "PlannerRuntime",
    "PersistedAdmissionContextRejected",
    "PersistedAnswerAuthorityProjector",
    "PersistedEvidenceAnswerAuthorityProjector",
    "PersistedAnswerAuthorityRejected",
    "PersistedAnswerCapabilityBoundaryProvider",
    "PersistedCapabilityAdapterError",
    "PersistedCapabilityAdapterFactories",
    "PersistedCapabilityBoundaryRejected",
    "PersistedConservativeContextTokenCounter",
    "PersistedContextAdapterFactories",
    "PersistedContextCandidateSource",
    "PersistedContextProjectionPolicy",
    "PersistedContextSnapshotStore",
    "PersistedLocalAdapterError",
    "PersistedLocalBoundaryInputsProvider",
    "PersistedLocalBoundaryRejected",
    "PersistedLocalRuntimeAdapterFactories",
    "PersistedRuntimeAdmissionContextProvider",
    "PersistedPlanCapabilityBoundaryProvider",
    "PersistedToolBoundaryPolicy",
    "PersistedToolCallBatchBoundaryProvider",
    "ProviderAdapter",
    "ProviderAnswerBlockProjection",
    "ProviderAnswerProjection",
    "ProviderDecisionProjection",
    "ProviderIntentUnderstandingProvider",
    "ProviderMainAgentActionProvider",
    "ProviderPlannerProvider",
    "PersistedMainAgentDecisionBoundaryProvider",
    "PersistedMainAgentTurnResolver",
    "PublishedAnswerMessage",
    "PureAgentRuntimeController",
    "RunningActionRecoveryContext",
    "RunningActionRecoveryController",
    "RunningActionRecoveryPlan",
    "PureAgentRuntimeComponentFactories",
    "PureAgentRuntimeComposition",
    "PureAgentRuntimeCompositionRoot",
    "ReplanCapabilityExecutor",
    "RequestInformationCapabilityExecutor",
    "RenderedAnswerCandidate",
    "ResponseCommitDecision",
    "ResponseLifecycleStatus",
    "ResponsePersistenceEnvelope",
    "ResponseStaleIntent",
    "ResponseStaleReason",
    "ResponseSupersedeReason",
    "ResponseVersionController",
    "ResponseVersionHead",
    "ReceiptOnlyAnswerAuthorityProjector",
    "RuntimeGuardSuite",
    "RuntimeCompositionError",
    "RuntimeCompositionStatus",
    "RuntimePolicyCeiling",
    "RuntimeProfileSnapshot",
    "RuntimeActionRecoveryBinding",
    "RuntimeWakeup",
    "SourceBasis",
    "StatementBlock",
    "StructuredModelCallBridge",
    "ToolCallBatchBoundary",
    "ToolCallBatchBoundaryProvider",
    "ToolCallBatchCapabilityExecutor",
    "ToolVisibilityProjector",
    "AnswerCapabilityBoundary",
    "AnswerCapabilityBoundaryProvider",
    "AnswerCapabilityExecutor",
    "build_initial_registry",
    "build_local_pure_agent_adapters",
    "project_provider_decision",
    "build_official_deepseek_adapter",
    "bootstrap_local_pure_agent_runtime",
    "build_capability_handler_registry",
    "create_running_task",
    "decide_transition",
    "freeze_registry_snapshot",
]
