from __future__ import annotations

import argparse
import asyncio
import json
import sys
from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
APP_DIR = ROOT / "AI_Middle_Office"
if str(APP_DIR) not in sys.path:
    sys.path.insert(0, str(APP_DIR))

from app.services.drawing_ocr_llm_cabinet_classifier import (  # noqa: E402
    build_ocr_llm_cabinet,
    read_context_packages_jsonl,
)


DEFAULT_CONTEXT_PACKAGES_JSONL = (
    ROOT
    / "outputs"
    / "biz2x_trial"
    / "ocr_cabinet"
    / "20260625_stage2_context_packages"
    / "ocr_context_packages.jsonl"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build BIZ-2x OCR LLM cabinet classifications.")
    parser.add_argument(
        "--context-packages-jsonl",
        default=str(DEFAULT_CONTEXT_PACKAGES_JSONL),
        help="Path to ocr_context_packages.jsonl generated by stage 2.",
    )
    parser.add_argument("--output-dir", default="", help="Defaults to outputs/biz2x_trial/ocr_cabinet/<run_id>.")
    parser.add_argument(
        "--sample-size",
        type=int,
        default=240,
        help="Representative sample size. Use 0 to classify all context packages.",
    )
    parser.add_argument(
        "--sample-strategy",
        choices=["representative", "first"],
        default="representative",
        help="How to choose packages for a stage-3 sample run.",
    )
    parser.add_argument("--max-nearby", type=int, default=16, help="Maximum nearby OCR evidences sent to the LLM.")
    parser.add_argument("--max-items-per-batch", type=int, default=30, help="Maximum OCR evidences per LLM batch.")
    parser.add_argument("--max-chars-per-batch", type=int, default=28000, help="Maximum JSON chars per LLM batch.")
    parser.add_argument(
        "--external-payload-mode",
        choices=["minimal", "full"],
        default="minimal",
        help="minimal omits image paths, bbox, tile ids, and precise relation distances from external LLM payloads.",
    )
    parser.add_argument(
        "--no-mask-sensitive-text",
        action="store_true",
        help="Do not mask likely title-block company/person/certificate/date text before sending to the LLM.",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Resume from classified_ocr_cabinet.partial.json in the output directory and skip completed text_ids.",
    )
    parser.add_argument("--max-retries", type=int, default=2, help="Retry count per LLM batch after a transient error.")
    parser.add_argument("--retry-delay-seconds", type=float, default=3.0, help="Base retry delay per LLM batch.")
    parser.add_argument("--execute", action="store_true", help="Call the selected classifier. Omit for dry-run preview.")
    parser.add_argument(
        "--provider",
        default="deepseek",
        choices=["deepseek", "dashscope", "qwen", "local", "mock"],
        help="Classifier provider. local expects an OpenAI-compatible chat completions endpoint on localhost or intranet.",
    )
    parser.add_argument("--model", default="", help="Optional model override.")
    parser.add_argument(
        "--local-chat-url",
        default="",
        help="OpenAI-compatible /chat/completions URL for provider=local, for example http://127.0.0.1:11434/v1/chat/completions.",
    )
    parser.add_argument("--local-api-key", default="", help="Optional bearer token for provider=local.")
    parser.add_argument("--trace-id", default="", help="Optional model gateway trace id.")
    return parser.parse_args()


async def main_async() -> None:
    args = parse_args()
    context_path = Path(args.context_packages_jsonl)
    context_packages = read_context_packages_jsonl(context_path)
    if args.output_dir:
        output_dir = Path(args.output_dir)
    else:
        run_id = datetime.now().strftime("%Y%m%d_%H%M%S_stage3_ocr_cabinet")
        output_dir = ROOT / "outputs" / "biz2x_trial" / "ocr_cabinet" / run_id

    report = await build_ocr_llm_cabinet(
        context_packages=context_packages,
        output_dir=output_dir,
        sample_size=args.sample_size,
        sample_strategy=args.sample_strategy,
        max_nearby=args.max_nearby,
        max_items_per_batch=args.max_items_per_batch,
        max_chars_per_batch=args.max_chars_per_batch,
        external_payload_mode=args.external_payload_mode,
        mask_sensitive_text=not args.no_mask_sensitive_text,
        resume=args.resume,
        max_retries=args.max_retries,
        retry_delay_seconds=args.retry_delay_seconds,
        execute=args.execute,
        provider=args.provider,
        model=args.model or None,
        local_chat_url=args.local_chat_url or None,
        local_api_key=args.local_api_key or None,
        trace_id=args.trace_id or None,
    )
    print(json.dumps({"summary": report["summary"], "outputs": report["outputs"]}, ensure_ascii=False, indent=2), flush=True)


def main() -> None:
    asyncio.run(main_async())


if __name__ == "__main__":
    main()
